### PR TITLE
added loot/drop tracking to packet

### PR DESCRIPTION
**Pull request by Roze-Myne**
Hey, I tired to keep the code style similar to your setup and added drop/loot tracking to the plugin. The code added just adds an extra property to the main json data called "loot" that sends some info about the thing that dropped the items along with the items dropped.

Let me know if you want me to change anything etc! (or if its not something you want as a part of this plugin)

### CODE REVIEW

**Comment by Rachnus** [comment]
Looked over it quickly and it seems good

I assume this is just for debugging `client.addChatMessage(xxx);`

Also believe `clientThread.invokeLater` is not required unless we're directly querying something from the game like inventory, I might be wrong though

Working on a couple changes on the front end, after that I will check this one out and merge if its all good

**Comment by Roze-Myne** [comment]
Thanks! The client.addChatMessage is just for debugging, I can do another commit removing it or I think I set it so maintainers can edit the commit before merge (new to github).

was not sure about the invokeLater part since this is the first runelite stuff I have worked on, so it should be fine to remove if you think so.

**Comment by Roze-Myne** [comment]
clicked the wrong button

**Comment by Rachnus** [comment]
Took a deeper look at at it now

What if the player manages to kill 2 or more mobs in the same tick, such as barraging or using chins, it will only send the latest, try and make some sort of loot queue so we don't miss anything.

Also rather than making the `items` field in the JSON output an object, make it an array

I'll merge after these things are done 👍

**Comment by Roze-Myne** [comment]
Switched over to array and removed the debugging chat adds

Also removed the invokeLater part, some imports got dropped by the IDE and it seemed to work without them, I can add them back in manually if needed!

**Comment by Rachnus** [comment]
Everything looks good, nice work, there's nothing on the front end to interpret this data yet but, atleast its there for usage, I'll add some health/prayer changes too before I push the release to the plugin hub

**Pull request merged**
